### ISSUE TITLE
Función para calcular el numero de hidratos máximo de un Ingrediente

### ISSUE THREAD

**Issue by Pablont98** [Pablont98/IV#30]
Se tendrá que desarrollar un metodo/funcionalidad que calcule los hidratos máximos de un ingrediente.

**Comment by JJ** [comment]
¿Ya has llegado a m5?

**Comment by Pablont98** [comment]
No entiendo la pregunta profesor

**Comment by Pablont98** [comment]
Tras la reestructuración del código del proyecto, el Milestone 5 (si es a lo que se refiere) va a desaparecer. Así como todos los issues referentes a la clase Ingrediente

**Comment by JJ** [comment]
Pues está en el milestone 5 este issue. Y el código que has añadido en este PR referencia este issue.
