### ISSUE TITLE
Creación de la clase Receta

### ISSUE THREAD

**Issue by vlljuan99** [Pablont98/IV#9]
Propuesta de la clase Receta en lenguaje Python, voy a añadir los siguientes atributos:
## Receta:
* Nombre
* Ingredientes -> array de dato tipo Ingrediente
* Tiempo de preparación
* Dificultad
* Elaboración
* Valor calórico

Está relacionado con la HU #7.

**Comment by vlljuan99** [comment]
¿Quizás debería de hacer también el TDA Ingrediente?

**Comment by vlljuan99** [comment]
¿La dificultad la quieres en un valor del 1 al 5?

**Comment by Pablont98** [comment]
* Habia pensado los ingredientes como un array de Strings y para que fuera mas sencillo. Pero todo es discutible, cual es tu opinión? 
* Sobre la dificultad entre 1 y 5 lo veo perfecto

**Comment by vlljuan99** [comment]
> * Habia pensado los ingredientes como un array de Strings y para que fuera mas sencillo. Pero todo es discutible, cual es tu opinión?

¿Pero cómo calculas el aporte calórico total? ¿No es mejor ir cogiendo las calorías de cada ingrediente y sumarlas en un método de la clase Receta?

> * Sobre la dificultad entre 1 y 5 lo veo perfecto

Ok, lo haré así restringido, que supongo que se puede.

**Comment by Pablont98** [comment]
> ¿Pero cómo calculas el aporte calórico total? ¿No es mejor ir cogiendo las calorías de cada ingrediente y sumarlas en un método de la clase Receta?

Cierto, no había caido en eso. Hazlo con el TDA Ingrediente y asocias a cada ingrediente su aporte calórico, con idea de luego meter alguna que otra tupla mas, como vitaminas y tal.

**Comment by JJ** [comment]
Buena discusión, que es lo que se busca en estos casos.
Los issues deben ser siempre problemas a resolver, no propuestas de cosas. Si no, estáis discutiendo sobre la nada en vez de ver qué es lo que sirve a la lógica de negocio.
